apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::671588136887:role/eksctl-my-simple-jwt-api-nodegrou-NodeInstanceRole-177VY8TYANU6Y
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolelearn: arn:aws:iam::671588136887:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-09-06T11:10:57Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "8977"
  uid: ed2f9e18-caa0-4d4f-bf5c-3aa34eb2ca1b
